"""数据导出服务 - Excel / PDF."""
import io
from datetime import datetime

from app.models import GroupInfo, Task, TeamReport, UserProfile


FREE_WATERMARK = "Generated by TeamMind AI Free — 升级 Pro 去除水印"


def _wrap_text(text: str, width: int) -> list[str]:
    lines = []
    while text:
        lines.append(text[:width])
        text = text[width:]
    return lines or [""]


class ExportService:
    """导出画像、分组、任务、报告."""

    def export_profiles(self, profiles: list, *, preview: bool = False) -> bytes:
        from openpyxl import Workbook

        wb = Workbook()
        ws = wb.active
        ws.title = "Profiles"
        ws.append(["用户ID", "专业", "知识分", "技能分", "协作分", "偏好角色"])
        rows = profiles[:5] if preview else profiles
        for p in rows:
            ws.append([p.user_id, p.major, p.knowledge_score, p.skill_score, p.collab_score, p.pref_role])
        if preview:
            ws.append([])
            ws.append([FREE_WATERMARK])
        buf = io.BytesIO()
        wb.save(buf)
        return buf.getvalue()

    def export_groups(self, groups: list, *, preview: bool = False) -> bytes:
        from openpyxl import Workbook

        wb = Workbook()
        ws = wb.active
        ws.title = "Groups"
        ws.append(["组ID", "组名", "成员", "均衡分", "平均技能"])
        rows = groups[:5] if preview else groups
        for g in rows:
            ws.append([g.id, g.group_name, g.member_ids, g.balance_score, g.avg_skill])
        if preview:
            ws.append([])
            ws.append([FREE_WATERMARK])
        buf = io.BytesIO()
        wb.save(buf)
        return buf.getvalue()

    def export_tasks(self, tasks: list, *, preview: bool = False) -> bytes:
        from openpyxl import Workbook

        wb = Workbook()
        ws = wb.active
        ws.title = "Tasks"
        ws.append(["任务", "负责人", "难度", "进度", "状态"])
        rows = tasks[:5] if preview else tasks
        for t in rows:
            ws.append([t.task_name, t.assignee_id, t.difficulty, t.progress, t.status])
        if preview:
            ws.append([])
            ws.append([FREE_WATERMARK])
        buf = io.BytesIO()
        wb.save(buf)
        return buf.getvalue()

    def export_report_pdf(self, report: TeamReport, group: GroupInfo, *, watermark: bool = False) -> bytes:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas

        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=A4)
        c.drawString(50, 800, "组队超脑（TeamMind AI）- 团队协作质量报告")
        c.drawString(50, 780, f"团队: {group.group_name}")
        c.drawString(50, 760, f"完成率: {report.completion_rate}%")
        c.drawString(50, 740, f"质量分: {report.quality_score}")
        c.drawString(50, 720, f"风险: {report.risk_level}")
        c.drawString(50, 700, f"生成时间: {datetime.utcnow().isoformat()}")
        y = 680
        try:
            import json

            detail = json.loads(report.detail or "{}")
            narrative = detail.get("llm_narrative") or {}
            summary = narrative.get("summary") if isinstance(narrative, dict) else None
            if summary:
                c.drawString(50, y, "AI 解读:")
                y -= 18
                for line in _wrap_text(str(summary), 90)[:6]:
                    c.drawString(50, y, line)
                    y -= 16
        except (json.JSONDecodeError, TypeError, AttributeError):
            pass
        if watermark:
            c.setFont("Helvetica", 9)
            c.drawString(50, 60, FREE_WATERMARK)
        c.save()
        return buf.getvalue()

    def export_super_group_report(
        self,
        *,
        class_name: str,
        health: dict,
        groups: list,
        nudge_summary: dict | None = None,
        watermark: bool = False,
    ) -> bytes:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas

        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=A4)
        y = 800
        c.drawString(50, y, "TeamMind 超级分组报告")
        y -= 24
        c.drawString(50, y, f"班级: {class_name}")
        y -= 20
        c.drawString(50, y, f"健康分: {health.get('health_score', 0)} | 画像完成 {health.get('profile_completion_rate', 0)}%")
        y -= 20
        c.drawString(50, y, f"任务完成 {health.get('task_completion_rate', 0)}% | 逾期 {health.get('overdue_tasks', 0)}")
        y -= 28
        if nudge_summary:
            c.drawString(50, y, f"待催办: 画像 {nudge_summary.get('no_profile', 0)} | 未参与活动 {nudge_summary.get('no_activity', 0)}")
            y -= 24
        c.drawString(50, y, f"共 {len(groups)} 个小组")
        y -= 20
        bd = health.get("breakdown") or {}
        if bd:
            c.drawString(50, y, f"健康分构成: 画像 {bd.get('profile_component')} + 任务 {bd.get('task_component')} + 风险 {bd.get('risk_component')}")
            y -= 20
        for g in groups[:12]:
            line = f"- {g.get('group_name', '')}: 技能 {g.get('avg_skill', 0)} | 知识 {g.get('avg_knowledge', '-')} | 协作 {g.get('avg_collab', '-')}"
            for seg in _wrap_text(line, 85)[:2]:
                c.drawString(50, y, seg)
                y -= 16
            note = g.get("complement_note") or (g.get("config") or {}).get("complement_note")
            if isinstance(note, str) and note and y > 100:
                for seg in _wrap_text(note, 80)[:1]:
                    c.drawString(60, y, seg)
                    y -= 14
            if y < 80:
                break
        if watermark:
            c.setFont("Helvetica", 9)
            c.drawString(50, 40, FREE_WATERMARK)
        c.save()
        return buf.getvalue()
